### ISSUE TITLE
crash during livestream

### ISSUE THREAD

**Issue by Raemon** [dspeyer/ritualEngine#100]
Html5.disposeMediaElement/<@https://vjs.zencdn.net/7.10.2/video.js:22635:14
Html5.disposeMediaElement@https://vjs.zencdn.net/7.10.2/video.js:22638:9
dispose@https://vjs.zencdn.net/7.10.2/video.js:21415:13
dispose@https://vjs.zencdn.net/7.10.2/video.js:23858:20
destroy@https://secularsolstice2020.org/widgets/Livestream.js:88:25
success@https://secularsolstice2020.org/test/partake:258:36
c@https://ajax.googleapis.com/ajax/libs/jquery/3.5.1/jquery.min.js:2:28294
fireWith@https://ajax.googleapis.com/ajax/libs/jquery/3.5.1/jquery.min.js:2:29039
l@https://ajax.googleapis.com/ajax/libs/jquery/3.5.1/jquery.min.js:2:79800
o/<@https://ajax.googleapis.com/ajax/libs/jquery/3.5.1/jquery.min.js:2:82254

**Comment by taymonbeal** [comment]
We gave up on livestreaming.
