### ISSUE TITLE
Crash after allowing microphone access

### ISSUE THREAD

**Issue by AdamScherlis** [dspeyer/ritualEngine#104]
immediately after clicking "initialize singing" and authorizing mic access during stress test:

"AbortError: The user aborted a request."

**Comment by taymonbeal** [comment]
I don't actually know what this is and I'm worried we won't be able to repro it...

**Comment by taymonbeal** [comment]
Asking user for help reproing

**Comment by taymonbeal** [comment]
We've fixed a lot of stuff, so I'm going to hope that we've fixed this too.
