### ISSUE TITLE
Reducing size of faces also reduces size of other page elements

### ISSUE THREAD

**Issue by EEdwardsA** [dspeyer/ritualEngine#105]
When I hit cmd - to make the faces take up a smaller portion of the screen, so that I could see the lyrics better, the faces did get smaller, but the background image moved and the scrollbar moved sideways (leftward), as well.

**Comment by Raemon** [comment]
This will most likely be handled by making it so faces don't take up so much room in the first place, a la https://github.com/dspeyer/ritualEngine/issues/107
