### ISSUE TITLE
Reorganizing Sizes of Faces

### ISSUE THREAD

**Issue by Raemon** [dspeyer/ritualEngine#107]
Daniel deliberately made the face-avatars at a size where they wouldn't take up too much space. I deliberately made them a  bigger because I thought it was important for at least some videos to be moderately large. 

I think both things are true. (I think it's important there be at least some faces you can clearly see singing)

I think getting this right requires a slightly different algorithm for organizing the faces, where maybe they can overlap more, or maybe they reduce in size faster. We could potentially have them crawl up against the left side of the screen, but I think we may need to save that space for videos of singers during songs.

(Note: I also made the faces back into pure circles. I had previously said "it's important to have the corners because otherwise it crops too much of my face", but now that I've seen the vision for how Lots of Faces Look Together, I thought it was pretty confusing to have them start out as squares and transition into circles, and that confusion wasn't worth the benefit of a little extra space. Meanwhile making the faces bigger solves the "crops too much of my face" problem)

**Comment by Raemon** [comment]
(I'm not sure they need to be _quite_ as big as I made them, or that the entire first row needs to be that big. I kinda like having at least one or two that are large-ish, but maybe most of the rest of the front-row could be smaller?)

**Comment by dspeyer** [comment]
Braindump...

The current algorithm in master (not sure about devel) is that size
decreases by 1/3 (so a factor of 2/3) each row, and y spacing is 3/2 the
larger radius aka 9/10 the distance we'd need to ensure zero overlap.  This
ensures the total vertical space is 5x the starting radius (2.5x starting
diameter).

(Or, rather, that's what it *would* be if everything were circles.  Squares
need a little extra vertical space, which is currently not accounted for
and total vertical space overflows a bit as a result.  Do you still really
want squares for the biggest videos?)

Letting Participants and Content overlap is certainly an option.  We need
to get z-indices right (Anna Tchetchetkine's screenshot shows that not
working in the big stress test) and to ensure all content copes tolerably
and most copes well with being layered over something.  In my opinion,
lyrics cope well and backing videos cope tolerably, so "mostly backing
videos" is incompatible with Participant/Content overlap but "backing
videos for 5000 Years and the end of Brighter than Today" is compatible.
Not sure what the current thinking on backing videos is.

We *could* say that Participants can overlap the bottom half of content but
not the top.  This would require script-writers to pay attention to what's
in the top or bottom half of slides, without any tooling to help.  It
breaks the heuristic of modularity and strikes me as likely to go badly
wrong.

We can claim the left side of the screen.  And the right on slides without
chat.  This would be somewhat tricky to code, and leads to a greater need
to test at varying screen resolutions.  Not sure it's worth the work.

We can also, of course, tweak both the falloff rate and the vertical offset
rate.

Related issue: When Chat is up, who gets the bottom right corner?  Seems
from this like Participants needs it more, but if you expect chat to flow
fast, maybe not.   In any case, they don't share well.

Also related: Content is currently centered left-right wrt the entire
window and may or may not overlap with Chat. This is probably not ideal,
but I'm not sure what is.

**Comment by Raemon** [comment]
1) I have concretely changed my mind about having squares. (I think the world where squares made sense had a more sharp division between "people in my Twilio room" vs "everyone else." In the world where you're deliberately blurring the line between videos and snapshots, I think having different shapes is more confusing than helpful.

I now think just using circles everywhere makes more sense.

2) "What's up with Chat?"

I just tried out an experiment with chat to make it take up less space without looking too weird. See this PR:
https://github.com/dspeyer/ritualEngine/pull/109

3) Overlapping

This will probably automatically get fixed when we have 100+ people, but at 20-40 people it feels like there's a lot of empty space that sits unused. I think it'd be probably be fine to overlap verticaly a bit more (but, I'd also make sure that people in subsequent rows appear "behind" the front rows).

4) FWIW I do like the idea of arcing the auditorium-layout such that the left and right edges creep up a bit on the screen.

5) random constraint on bandwidth that's somewhat relevant:

I think 26 is way more videos than we actually need here. I think it'd be basically fine to only have the 6-12 people have videos, and then just rotate semi-frequently who's in those 12 slots. (this'll probably be a separate issue but felt relevant to how we're conceptualizing the audience section)
