### ISSUE TITLE
Figure out lyric-timing source

### ISSUE THREAD

**Issue by dspeyer** [dspeyer/ritualEngine#111]
The lyric system currently assumes there is a single lead singer who is also clicking in the lyrics in time.  In a more backing-track-driven setup, we need a prerecorded lyric timing source.  It should be reasonably easy to generate whatever we use from the backing track.

**Comment by Raemon** [comment]
So, if you're trying to highlight individual lyric-lines, you need the timing pretty precise. But I think if we were just generally scrolling the lyrics to keep the right ones in mid-screen, it'd be fine to use a heurstic-based "check the entire duration of the song, and just scroll one lyric line per N seconds", where N is "duration / number of lyric lines"

**Comment by dspeyer** [comment]
This is fixed in the newslots branch.  I guess the bug should stay open
until that's merged.
