### ISSUE TITLE
On page refresh, I sometimes briefly see the error-screen

### ISSUE THREAD

**Issue by Raemon** [dspeyer/ritualEngine#115]
(It flickers in briefly and then flickers out). I only see it sometimes. I _think_ I only see it on Firefox, although I'm not sure. I don't see it when I first open the page for the first time.

(I think it's fine to leave Firefox as the somewhat jankier version that we steer people away from, but let them use if they prefer it, so this may not be very high priority).

**Comment by taymonbeal** [comment]
Does this still happen post-Sentry?

**Comment by Raemon** [comment]
I'm going to close it for now, and re-open if it comes up again.
