### ISSUE TITLE
Trouble with garbage-collected Twilio rooms

### ISSUE THREAD

**Issue by dspeyer** [dspeyer/ritualEngine#118]
If you start a ritual, close all tabs connected to it, wait sufficient time (1 minute?) and try to reconnect, you'll get errors.  Twilio will have garbage-collected the room, and ritualEngine can't cope with that.  I'm not sure what the correct behavior is, but locking up with an error message isn't it.

**Comment by taymonbeal** [comment]
Fixing this is a bit complicated. We'd need to catch the error and then ask the server for a new token. The server, when asked for a new token in this way, would need to use the API to make sure that the room still exists (which would require this endpoint to be async), and if not, to create a new room. We might also need some locking to ensure that it wouldn't try to create more than one room if this happened to more than one user (although we might be able to reuse the existing locking for that).
