### ISSUE TITLE
Design new Intercom start experience

### ISSUE THREAD

**Issue by taymonbeal** [dspeyer/ritualEngine#130]
We should decide whether we want to stick with the default button, or instead create some other kind of button that might fit better with the site design. One possibility I'm imagining is moving the chat form back to the bottom-right (where it makes more sense), and then putting a "I Need Tech Support" button (with horizontal proportions, not round like the Intercom button) below it. Then maybe we could incorporate an onboarding step where people click through that.

Would we put the tech support thing over the chat, or to the right of it, though?

**Comment by dspeyer** [comment]
Is the intercom button supposed to be always on or just on the welcome
slide?  The welcome slide has chat disabled (in the current version, but I
think this is also the plan).

I oppose moving chat to the bottom of the screen.  Getting good avatar
arrangement was tricky enough.  Doing so with less space and weirder
shaping constraints is likely to go badly.

It occurs to me that the top left is currently empty except for /lead (who
presumably will not need intercom).  That might be too visually prominent.

**Comment by taymonbeal** [comment]
Intercom is supposed to be available all the time.

Is the chat box supposed to move as chat messages get sent? I think it does that now, and this seems pretty unusual. And pinning it at the top isn't great either, because the standard UX pattern is that it goes near where the message that you're composing will be moved to after you sent it. This is why the box is usually at the bottom. I'm not sure what to do about this.

(Note that we will not need the username box once we start asking people for usernames in the onboarding flow.)

Top-left might be too visually prominent, but on the other hand we don't want people to miss this. I'd like to know what @Raemon thinks.

**Comment by Raemon** [comment]
Yeah this is tricky. I see what Taymon is getting at with integrating with
with chat. But, I think the current chat-layout took a fair amount of
finangling to work, and am pessimistic we'll get anything better.

I do like the idea of putting intercom near the new-chat button (because
otherwise people will probably use the chat for tech support, which we
mostly don't want)

I will reflect on this more tomorrow and try playing around with it.

**Comment by taymonbeal** [comment]
Current plan IIUC is putting this among the bottom-bar buttons.

**Comment by Raemon** [comment]
A slight nice-to-have is being able the give the tech support button an additional css class during the opening slide that makes it bigger. But, this is fairly low priority.

**Comment by dspeyer** [comment]
Bottom button bar now has an extra class during welcome.  Moved tech support's oversizedness into the welcome-only css.  It's all css, so it should be easy to tweak further.
