### ISSUE TITLE
Fix the bad annoying SVG errors

### ISSUE THREAD

**Issue by taymonbeal** [dspeyer/ritualEngine#134]
They show up in the console every time and I'd rather have console errors always correspond to real problems.

**Comment by Raemon** [comment]
Can we use the humanistculture logo that is also used for the
un-set-avatars? I'm not sure how to do that, if you know how to copy-paste
that into a place where favicon can use it that'd be helpful to me.

**Comment by taymonbeal** [comment]
Did you mean to post this on #135?

**Comment by taymonbeal** [comment]
Not going to address this for Solstice.
