### ISSUE TITLE
Speech/Song transitioning

### ISSUE THREAD

**Issue by Raemon** [dspeyer/ritualEngine#139]
This is annoying, but important:

The 500 Million Speech is directly integrated with the song Brighter Than Today (the beginning of the song overlaps with the end of the speech). This requires them to work on a single slide. Theoretically the whole thing could just be bucket-powered, but then you'd have people shuffling in their seats making noise during the speech, being disruptive. Somehow we want people muted during the speech, but not the song.

There are about 40 seconds at the beginning of the song that are instrumentals or soloist, where it's okay if we take awhile to get everyone properly synced into the song.

The backup-backup plan is to just not actually use bucket brigade for Brigher Than Today (and instead rely on having a lot pre-recorded singers to make it feel like you're singing with people) But, this is quite sad to have to fall back to.

Taymon's idea was setting up a trigger for users to mute themselves at the beginning and then unmute themselves, which we already have API for.

**Comment by dspeyer** [comment]
Running the slide as bucketsinging, but with mics muted and lyrics hidden
until the -4 event should be pretty easy

**Comment by Raemon** [comment]
Now that backing-video-sync is working, I think for Brighter Than Today it'd actually be better to just have the lyrics be part of the video anyway (it'll need to be a fullscreen video), so don't even need to do "hide lyrics"

**Comment by dspeyer** [comment]
Lyrics visible for the entirety of the spoken part?  That feels like both a
spoiler and a distraction

**Comment by Raemon** [comment]
The lyrics would appear in the video timed with when they're getting sung.

**Comment by Raemon** [comment]
(the lyrics would be literally part of the video, just pixels appearing in time. I think this is how Brighter Than Today and Five Thousand Years should handle it since they have more immersive visuals)

**Comment by taymonbeal** [comment]
What did we decide to do about this?

**Comment by Raemon** [comment]
There needs to be some kind of timing event that mutes everyone at the start of the event, and unmutes them at a specific later time.

**Comment by Raemon** [comment]
I'm not sure enough about the implementation details to specify further. But can chat through it if you have more specific questions and are up for giving a go at it.
