### ISSUE TITLE
Indicate more clearly which video is you

### ISSUE THREAD

**Issue by taymonbeal** [dspeyer/ritualEngine#140]
Maybe always put the user in the bottom-left corner? Or just outline the circle specially or something?

**Comment by Raemon** [comment]
bottom-left seems good to me. I think this might already be the case?

**Comment by taymonbeal** [comment]
When I log in by myself I get put in the bottom center.

**Comment by dspeyer** [comment]
It's always bottom left unless you're the only one there, because just
bottom left looks silly

**Comment by taymonbeal** [comment]
I guess this is good enough.
