### ISSUE TITLE
Clarify/improve specs on SVGs

### ISSUE THREAD

**Issue by Raemon** [dspeyer/ritualEngine#143]
Daniel, I'm interested in questions about the rules for SVGs as they currently are, and some thoughts how they probably should be. 

(this may be the sort of thing clashing with your abstractions on how everything works, if so, sorry about that. I do suspect it's necessary for me to have some flexiblity in how to render videos and slides based on my own aesthetic judgment)

Considerations:

**1.** I *think* there will need to be roughly 3 types of videos. I'm not actually sure if this is comprehensive yet because I haven't tried to build the setlist yet.

a) 300x300ish circle videos, which should be positioned to the left of the lyrics (this looks like what it's actually designed for right now).
b) occasionally, we may need non-circle videos positioned off to the left (probably rectangles). 
c) for at least a couple songs, we will have fullscreen videos (width set to 100%). These might handle their own lyrics as part of the video, or might be designed to leave space for the existing lyrics engine, I haven't decided.

So, there should be some way to handle those three types. I think I'd probably prefer if the engine _wasn't_ that opinionated about exactly how to render the videos, and I just style them with manual css (maybe passed in through a parameter in the BucketSinging widget)

...

**2.** I'm not yet sure about non-BucketSinging-videos. I think they will most likely all be full-screen videos.

**3.** The current implementation on solsticeStressTest has a very wide area for text, which looks wonky. (I'd prefer the text in a smaller central column). I'm guessing this is totally fine within the current SVG paradigm but figured I should flag it.

**Comment by dspeyer** [comment]
Standard layout (configurable in index.json) gives the top 70% of the
screen to content and the bottom 30% to participants (copied from the
drawing you sent me).  Participants overflows its allocation a little on
the left and right, but not the center.  Assuming the user's screen is
16:9, this leaves a roughly 5:2 space for content.  If the user's screen is
a different shape, the content will be shrunk to fit without distortion.

The svg can contain anything an svg can normally contain.

For slides with widgets (approximately all of them) it can also contain
boxes onto which the widgets will put their UI.  The colors of these boxes
match the colors in the corresponding json file.  They must be the only
things of those colors in the svg, and so should be colors you aren't
likely to use in general.

The boxes do not need to be rectangular.  Anything SVG handles as a rect or
path will do.  However, the widget will look at the containing box when
placing its UI.

This setup is designed for visual designing.  You can drag things around
and look at them.

The BucketSinging widget takes two boxes: one for lyrics and one for
video.  If you only specify one box, it will be used for both.  Soon it
will take a third, for the bucket info thingy.

At present, the video will always be rounded.  If the box for the video is
narrower than the video's native dimensions, the center will be shown.  If
the box is wider than the video's native dimensions, it will look silly.
Soon there will be a flag in the json to not round it, in which case if the
aspect ratios don't match I think it will be on the left or top as
appropriate, but I'm not sure (if you want some particular behavior, let me
know).  It would be nice if you could just draw a circle or rectangle as
you choose and the widget would understand that, but that would be hard to
implement so it'll be a json flag.

Regarding lyric box widths: yes the slides I designed have it wider than in
your drawing.  I tried copying directly, but some lines of lyrics didn't
fit and it looked really bad.  If you want narrower boxes, you'll need to
add line breaks to the lyrics manually.  At present, lyrics are 17pt but
lyric boxes are a fraction of the total screen, meaning that what lyrics
fit in what box will vary from screen to screen.  We could change that, at
the risk of making all our lyrics unreadably small on small screens, but
probably better to leave safety margins.

Similarly, chat overlays content and has a width set in pixels.  So you
never know how much of the right hunk of content will have that overlayed.

I strongly advise against putting lyrics into the video:
* At low resolution, it'll pixelate (even at moderate resolution, it'll
pixelate more than true text)
* At high resolution it will glitch on weak connections
* It makes the font size a function of the screen size
* It breaks the participants rotation

Not technically svg, but other slide json parameters of interest:
* bkZoom/bkZoomCenter: lets you zoom into an area of the background.
Useful for the traveling forward effect without clogging the pipes with
more background images
* chatClass: can be "normal" (white-on-black), "bow" or "hidden"
* bsBkg: BucketSinging-specific background options:
  * zoomSpeed / zoomCenter: zooms in a little each lyric advancement
  * backgrounds: a map from lyric numbers to background images

Also note that showParticipants, rotate and bkgAll are index.json
properties which do nothing on a slide.

**Comment by Raemon** [comment]
clarified enough for now.
