### ISSUE TITLE
Make it so that you can't navigate to a slide that doesn't exist

### ISSUE THREAD

**Issue by Raemon** [dspeyer/ritualEngine#149]
Currently, if you navigate to slide 0 or slide maxN+1, you get a mysterious crash.

I think this probably won't impact solstice itself but it's pretty common for slide-controlling-people to fingerslip and go to a wrong slide, and it sometimes interacts poorly with other slide-bugs. It seems fairly obviously like something that is supposed to be fixed in the final version of ritual engine.

**Comment by dspeyer** [comment]
Done
