### ISSUE TITLE
Failed to execute 'removeEventListener' on 'EventTarget': 2 arguments required, but only 1 present.

### ISSUE THREAD

**Issue by gwillen** [dspeyer/ritualEngine#154]
https://sentry.io/organizations/secular-solstice/issues/2093015853

On line 357 of `bucketSinging.js`:

```
            removeEventListener(this.clientErrorListener);
```

should be

```
            removeEventListener('error', this.clientErrorListener);
```

**Comment by dspeyer** [comment]
I fixed this in the process of writing the bucket control

**Comment by gwillen** [comment]
Shoot, this time it's my turn to be out of date, as it looks like this was fixed about an hour before I filed it. Sorry about that!
