### ISSUE TITLE
Bucket Brigade crash probably when SingerClient is created too early? (Not sure if already fixed.)

### ISSUE THREAD

**Issue by gwillen** [dspeyer/ritualEngine#158]
Creating this for https://sentry.io/organizations/secular-solstice/issues/2093019069 .

I don't know whether this exists or is fixed in current ritualEngine, and I don't know if it's seen frequently at all, but it looks like "Cannot read property 'port' of null" in any of a number of functions in bucket brigade code. 

If we see this again we should figure out how it's happening, but it's conceivable that it's already fixed.

**Comment by taymonbeal** [comment]
I'm just going to hope this is already fixed since we haven't seen it recently.
