### ISSUE TITLE
Onboarding flow doesn't realize that it can't get the camera

### ISSUE THREAD

**Issue by taymonbeal** [dspeyer/ritualEngine#160]
This is while I have Zoom open (which is expected to make the camera not available).

![Screenshot 2020-12-15 192053](https://user-images.githubusercontent.com/1991427/102288535-b1320400-3f0a-11eb-956b-f1ae3a0f9709.png)

**Comment by dspeyer** [comment]
Fixed I think.  Please test in windows with zoom.

**Comment by taymonbeal** [comment]
Tried, but am getting https://sentry.io/share/issue/a83a6971aa194e57a1072a29c4253439/.

**Comment by dspeyer** [comment]
Fixed some more

**Comment by taymonbeal** [comment]
Yay
