### ISSUE TITLE
Unclosed things in ritualEngine server

### ISSUE THREAD

**Issue by taymonbeal** [dspeyer/ritualEngine#161]
https://sentry.io/share/issue/11fac7e10b50473c957cb9e8d590168a/
https://sentry.io/share/issue/3d4e69609803488db1625b36fb53f446/

**Comment by gwillen** [comment]
I assume these are just supposed to be ignored but @dspeyer is presumably the expert.

**Comment by dspeyer** [comment]
Do we know what's issuing this error message or what it means?

**Comment by taymonbeal** [comment]
It means that there's an `aiohttp.ClientSession` somewhere in the rE server that didn't get closed like is supposed to happen.

In any event, not going to deal with this for Solstice.
