### ISSUE TITLE
Audio and video cut out during bucket singing

### ISSUE THREAD

**Issue by Raemon** [dspeyer/ritualEngine#169]
Jeff thinks maybe wifi failure related

![image](https://user-images.githubusercontent.com/3246710/102435094-e2720900-3fca-11eb-98b1-d6891670d5c7.png)

![image](https://user-images.githubusercontent.com/3246710/102435081-dab26480-3fca-11eb-9e06-f917351a782b.png)

**Comment by gwillen** [comment]
I think it's reasonable to suspect that this is due to wifi cutting out but it's a bit tricky to be sure.

**Comment by taymonbeal** [comment]
#173 should help. Not much else we can do.
