### ISSUE TITLE
Trivia doesn't work for Ray (at least locally)

### ISSUE THREAD

**Issue by Raemon** [dspeyer/ritualEngine#17]
If this turns out to be annoying to fix, it's not a high priority. I'm not even sure I want to use Trivia. But, if it were cheap to fix I'd want to be able to experiment with it.

**Comment by dspeyer** [comment]
Short of "Be Ray", any idea how to duplicate?

**Comment by Raemon** [comment]
Most notably I'm on a macbook, 10.14.6. I'm guessing the thing to do is
have a block of time where we're generally trying to debug everything going
weirdly on my machine, where I try some things, report errors, if there
aren't very clear errors maybe adding some more error logging, repeat.

**Comment by taymonbeal** [comment]
We decided not to have trivia.
