### ISSUE TITLE
Video doesn't start properly if you join bucket brigade partway through

### ISSUE THREAD

**Issue by taymonbeal** [dspeyer/ritualEngine#171]
I think this is because we miss the backingTrackStart event. We need a way to know that that's happened so we can start playing.

Blocked by: gwillen/solstice-audio-test#111

**Comment by dspeyer** [comment]
We *had* a thing where if you connect after events have gone by, they all
fire at once.  Did that get dropped in a shuffle?

**Comment by taymonbeal** [comment]
Seems to work now. I had a failure at one point but am going to hope it was the result of another bug.
