### ISSUE TITLE
Cannot read property 'srcObject' of undefined

### ISSUE THREAD

**Issue by taymonbeal** [dspeyer/ritualEngine#176]
https://sentry.io/share/issue/c91a38ac393a4e83af48058b79ed1b1c/

**Comment by dspeyer** [comment]
Any hints or guesses on repro steps?

**Comment by taymonbeal** [comment]
I had a bucket-singing video open with Ray when I ran into this.

**Comment by dspeyer** [comment]
I've pushed an amelioration.  I'll come back to this and try to repro it later.

**Comment by dspeyer** [comment]
Probably fixed.  Well, at least two scenarios that can cause this are fixed.
