### ISSUE TITLE
"Forget it; I'll be uncalibrated" button doesn't work

### ISSUE THREAD

**Issue by Raemon** [dspeyer/ritualEngine#178]
When I click this button on this screen, it consistently doesn't work:

<img width="1074" alt="image" src="https://user-images.githubusercontent.com/3246710/102550816-5536bf00-4073-11eb-9b94-e87ed16d97ed.png">

I get this:

BucketSinging.js:210 Uncaught (in promise) TypeError: Cannot read property 'success' of undefined
    at initContext (BucketSinging.js:210)
    at async Module.welcome (BucketSinging.js:529)
    at async welcome (welcome.js:151)
    
<img width="421" alt="image" src="https://user-images.githubusercontent.com/3246710/102550939-94fda680-4073-11eb-9b3d-f284383d756b.png">

**Comment by dspeyer** [comment]
Fixed
