### ISSUE TITLE
Create mail forwarding alias from secularsolstice.com or secularsolstice2020.org

### ISSUE THREAD

**Issue by taymonbeal** [dspeyer/ritualEngine#18]
Needed for Intercom.

**Comment by dspeyer** [comment]
I can easily create an mx record.  A mail forwarding server is a bit more work...  Unless I'm missing something?

**Comment by taymonbeal** [comment]
Please set the following records at the domain root:
MX mx1.improvmx.com. 10
MX mx2.improvmx.com. 20
TXT v=spf1 include:spf.improvmx.com ~all

**Comment by dspeyer** [comment]
Done (I think)
