### ISSUE TITLE
Use Hacky Headphone Heuristics to prevent people from being assigned to any but the last bucket

### ISSUE THREAD

**Issue by Raemon** [dspeyer/ritualEngine#180]
Based on the previous thread, I think we should probably do this. I think *probably* Taymon can do this but might need some help from Daniel. 

This'd require changing the bucket-assignment function, as well as disabled the bucket-choosing-buttons.

**Comment by taymonbeal** [comment]
What I'm going to do is, if in the beginning setup we think they might not be wearing headphones, display messaging that encourages them to skip calibration (but allows them to calibrate if they want, because the heuristics can be wrong).

**Comment by taymonbeal** [comment]
Decision was not to attempt this change this late; it's not quite sufficiently risk-free.
