### ISSUE TITLE
"Forget my info" button should exist

### ISSUE THREAD

**Issue by Raemon** [dspeyer/ritualEngine#181]
I think this actually might be best assigned to @gwillen

**Comment by gwillen** [comment]
So, I provided a function called wipeSavedParameters() in lib.js, and all you have to do is call it. Given that, and given that I don't know anything about UI stuff, it might be easier for you to do it? But I can if you still prefer.

Glenn

**Comment by Raemon** [comment]
I mostly don't have time to do it but if someone else can (maybe Taymon)
that'd be helpful.

**Comment by dspeyer** [comment]
This seems to have happened
