### ISSUE TITLE
Explicitly catch getUserMedia errors and handle them with some kind of useful error message

### ISSUE THREAD

**Issue by taymonbeal** [dspeyer/ritualEngine#186]
This includes:
- The call to getUserMedia in lib.js
- The calls to Twilio.Video.createLocalVideoTrack and Twilio.Video.createLocalAudioTrack in avatars.js

These are likely to be problems with the user's setup, so we should inform them of this and provide some sort of reasonable fallback.

(I've definitely seen some OverconstrainedErrors at some point but not totally sure which call sites they came from. Ideally we should just make sure we've covered all of them.)

**Comment by dspeyer** [comment]
The welcome case is caught.

The avatar case is not, but we make sure to test the webcam in welcome
(even if it's saved), so finding a problem at avatar-time is unlikely.

The lib.js case isn't used in the solstice script.  It's for
photocollage and login.

**Comment by taymonbeal** [comment]
Sounds good enough for now.
