### ISSUE TITLE
Decide whether clear-state button should refresh the page

### ISSUE THREAD

**Issue by taymonbeal** [dspeyer/ritualEngine#188]

**Comment by dspeyer** [comment]
My feeling is it should.  Otherwise, understanding what it does requires
too much knowledge of our internals.

What's the case for not?

**Comment by taymonbeal** [comment]
@gwillen, did you have reason to think that it should not?

**Comment by gwillen** [comment]
I thought it would be surprising and disruptive to the user to have the page refreshed by an innocuous-looking button that doesn't say 'refresh' on it, and which you wouldn't suspect would do that (without too much knowledge of our internals.)

As a compromise: When the user clicks it, can I put up an alert() that suggests refreshing, but doesn't actually do it?

**Comment by taymonbeal** [comment]
Can we change the button label to "Delete saved settings and reload" or "Forget me and reload"? I agree that it should say that it reloads, but I'm worried it will leave people in a confusing state if it does not reload.

**Comment by gwillen** [comment]
Per conversation on facebook messenger, I'm fine with changing it to something like "Delete saved settings and reload". Let me know if you want me to do it, otherwise I'm assuming you will.
