### ISSUE TITLE
Set up Intercom

### ISSUE THREAD

**Issue by taymonbeal** [dspeyer/ritualEngine#19]
Blocked by: #18

**Comment by dspeyer** [comment]
What is Intercom and why might we want it?

**Comment by taymonbeal** [comment]
Intercom is the thing on the bottom-right corner of lesswrong.com and many other websites, where you click a button, get a chat window where you can enter a problem you're having, and then a human comes and helps you. The plan IIUC is to have this be the primary means of getting tech support if you need it.
