### ISSUE TITLE
Redirect www.secularsolstice2020.org to secularsolstice2020.org

### ISSUE THREAD

**Issue by taymonbeal** [dspeyer/ritualEngine#194]
Users are likely to wind up here by accident.

Instructions: https://aws.amazon.com/premiumsupport/knowledge-center/redirect-domain-route-53/

**Comment by dspeyer** [comment]
Umm... I don't think we can do this as pure DNS.  We use HOST headers for multiplexing at the nginx layer, and our https certs aren't wildcards.  Doesn't this mean we need 403s from nginx?  And a fresh cert for handling https://www.secularsolstice2020.org?

**Comment by taymonbeal** [comment]
If we follow the above instructions, we will not be pointing the www A record at our nginx server. Instead, it will point to an S3 bucket that is configured to respond to all requests with a redirect. So no changes at all are needed in our server, only in Route 53 and S3.

The above instructions do not handle https://www.secularsolstice2020.org, but that can be fixed by adding a Cloudfront distribution on top. Or we could just ignore it, on the grounds that this error will probably only be encountered by people manually typing the URL, and they probably won't type https://.

**Comment by taymonbeal** [comment]
Alternatively, we could do this in nginx instead. (We don't need a wildcard cert, we just need one with two hostnames, Certbot should be able to handle that. It should only be a few lines of config; we already do something very similar to redirect HTTP to HTTPS. If you like you can just make the A record and then I can do the config.)

**Comment by dspeyer** [comment]
I don't think it's likely enough to come up to justify the risks or effort at this hour.  Most people will be clicking links, and nobody copy-typing a url prepends www
