### ISSUE TITLE
Figure out what to do about "Warning: timed out creating twilio local audio track"

### ISSUE THREAD

**Issue by taymonbeal** [dspeyer/ritualEngine#195]
@dspeyer, is this a thing that's just a one-shot occurrence? If so, would it make sense to use the error box that Ray had me create? It's kind of out there not integrated with any of our other messaging and not sure if we should do anything about that

**Comment by dspeyer** [comment]
What error box?

I'll grant the message isn't the most user friendly, but isn't the current setup that errors go to Sentry if that's configured, and are silently ignored otherwise?

**Comment by dspeyer** [comment]
Now I understand what error box.  While a similar design may be good (come to think of it, the design is pretty similar) this is definitely a different message.  Something like: 
"Could not set up mic for lobby.  This will not effect BucketSinging or text chat."  Maybe in the bottom left, near the mute buttons?  And suppress it if they clicked "I guess no one will hear me".

**Comment by taymonbeal** [comment]
Current work in progress at https://github.com/dspeyer/ritualEngine/compare/master...taymonbeal:twilio-audio-error. See blocking issue for what I'm waiting for to finish it.
