### ISSUE TITLE
secretId too small

### ISSUE THREAD

**Issue by jeffkaufman** [dspeyer/ritualEngine#199]
```
secretId = Math.round(Math.random()*1e9);
-- https://github.com/dspeyer/ritualEngine/blob/master/widgets/BucketSinging.js#L104
```

This hands enough of a risk of conflicts that I would feel safer if you increased it.

I'd recommend `Math.round(Math.random()*Number.MAX_SAFE_INTEGER)`.  This is under 2^64, which is what BB requires.

I would send a PR, but I'm not familiar enough with the ritual engine code to be sure this wouldn't break anything

**Comment by dspeyer** [comment]
Are you sure javascript won't "helpfully" treat that as a float and deliver
it in scientific notation?  It's your protocol, but ISTR trouble with that
happening elsewhere.

**Comment by dspeyer** [comment]
It's fundamentally BBS so I'll trust Jeff.  Done.
