### ISSUE TITLE
Degrade or disable videoconferencing when bucket brigade can't keep up with load

### ISSUE THREAD

**Issue by taymonbeal** [dspeyer/ritualEngine#20]

**Comment by dspeyer** [comment]
Done (by decreasing nvideos) but not well tested

**Comment by taymonbeal** [comment]
Is there anything we should do to test it?

**Comment by dspeyer** [comment]
Gather a dozen singers to run a test, then stack burdens on clients and see
if they down-video correctly.  We should probably figure out something
about appropriate burdens.

I tried running five tabs and my computer got very slow, but it's not
really equivalent and it was hard to tell what was happening.

**Comment by dspeyer** [comment]
So apparently the code that's in doesn't work.

I can certainly fix the bugs that were discussed.  I'm not sure I can run a good test.

**Comment by taymonbeal** [comment]
If we had robots, would they help run a good test? Because I still have robot-minutes available.

**Comment by dspeyer** [comment]
I fixed the known bugs.

If the robots can send both video and audio, that should get us most of the way there.  Then you just need a way to trigger lag locally (open facebook in 10 other tabs?)

**Comment by taymonbeal** [comment]
The robots can absolutely send both video and audio. Let me know in chat when you're available to run the test together?

**Comment by dspeyer** [comment]
This worked, or at least did not fail horribly
