### ISSUE TITLE
Micless + Sentry = Eternal Restart

### ISSUE THREAD

**Issue by dspeyer** [dspeyer/ritualEngine#202]
Bucket Brigade welcome uses a timeout to detect mic enumeration failure.  This is necessary because under some circumstances (I think involving locks) it can hang.  But it can also reject the promise, which gets ignored.  Under until-recently mode, this meant a little spam in the console log.  With local error handling, a big spurious "NotFoundError: Requested device not found" error.  And with Sentry, a refresh immediately after clicking "I guess no one will hear me".

I think there are a few other cases like this: where an unhandled error is actually ok, so extra sentry logic would be preferable.  If that's not possible, we can try to find all the cases and stick .catch() on the promises.

**Comment by taymonbeal** [comment]
How should we distinguish between cases that break the page and cases that don't?

**Comment by dspeyer** [comment]
I was hoping you'd think of something on the sentry side...

This one scares me.  I did a bunch of dev on the assumption that excess exceptions were harmless.  And I think most of us were working with no way to notice them.

I'll try to go through with the fixed error handling and test all the scenarios involving mics and webcams.

As a minimal fallback, can we get a ?nosentry that sets errorhandler to empty string while loading the page?

**Comment by taymonbeal** [comment]
I know of no way in principle that we can know, given an exception that we didn't specifically plan for, whether it is safe to proceed through it or whether it is indicative that the state is unfixably messed up. I did float the idea yesterday of always just trying to keep going, and @gwillen did not think it was a good idea, so we rejected it. I'm sorry if I hadn't been sufficiently clear about this but I don't know what else I could have done.

?nosentry is straightforward, I can do that.

The conceptually right way to approach this is to have a `catch` block or call in each place that might legimately/recoverably reject or throw, and do the appropriate handling there.

**Comment by gwillen** [comment]
I am not an expert on Ritual Engine exceptions -- I would prefer that exceptions propagated outward from Bucket Brigade are treated as fatal and result in a page reload (or whatever), but if the Ritual Engine experts would prefer things just proceed on exception coming from rE, I have no objection to whatever your best judgement on this is.

**Comment by dspeyer** [comment]
It gets worse...

Here's one of the stack traces:
  force_permission_prompt @ app.js:43
  async function (async)
  force_permission_prompt @ app.js:41
  wait_for_mic_permissions @ app.js:54
  async function (async)
  wait_for_mic_permissions @ app.js:46
  MicEnumerator @ app.js:66
  initContext @ BucketSinging.js:119

When initContext invokes wait_for_mic_permissions, there's a catch clause.
But when wait_for_mic_permission invokes force_permission, there isn't.
Nor is it awaited.  Instead a related event is awaited.

AFAICT, nothing I put in initContext will keep force_permission's
exceptions from going straight to sentry.

We could fix this in BBS.  I fear there may be similar in twilio where we
can't.

Looks like the code that refreshes is code we control.  And it has access
to the exception there.  So... maybe something.

**Comment by gwillen** [comment]
I would hope that these would all be our fault -- Twilio shouldn't be throwing top-level exceptions, isn't stuff like Sentry reasonably common that people would be used to keeping this stuff clean?

But if nonfatal uncatchable toplevel exceptions are something we have to deal with regularly, I do see the argument for switching over to just swallowing unexpected exceptions. It's not great because it can leave people just stranded on a broken slide with no way to know that it's broken unless they refresh the page manually. I don't know what we can do about that.

@dspeyer I get the impression that you don't expect that to happen? (Fatal exceptions that in fact do break the page so that it can't proceed?) I think maybe I had opposite intuitions about which case is most likely, but frankly I am not a JS dev, I just play one on TV.

**Comment by gwillen** [comment]
As to wait_for_mic_permissions, I think there were originally awaits in there, but they got refactored out at some point. I'm happy to rework it so that it shouldn't allow exceptions to escape, or so that we just catch them and return null or something.

**Comment by taymonbeal** [comment]
Twilio's APIs for opening WebRTC devices can throw. Therefore, calls to them should be surrounded by catch blocks or calls. I think we already audited all those sites and determined that they were okay, though. (There was one case where we just threw a fatal exception, but you told me that you considered it unlikely to come up in practice.)

I don't think Twilio should ever make top-level errors that we can't catch.

**Comment by gwillen** [comment]
I will fix the mic permissions stuff, without regard to the Larger Questions for the moment, so that it absorbs errors internally and neither throws them nor hits the toplevel handler.
