### ISSUE TITLE
Thoroughly test welcome flow with every convoluted mix of setup we can find

### ISSUE THREAD

**Issue by dspeyer** [dspeyer/ritualEngine#223]
We've changed a lot of code in a little time, and need to make sure that no/one/many/blocked/allowed/locked cameras and mics work ok.

(Well, not multiple mics.  We're not trying to support that.)

**Comment by dspeyer** [comment]
I tested all the ones *I* could think of and they worked fine.

(Except that one of the dialogs didn't fit, so I tweaked the size on that)

**Comment by taymonbeal** [comment]
Any further testing that we should be doing?

**Comment by dspeyer** [comment]
I just tried denying mic permissions and got stuck with an error.  I think this used to work.  Did someone change something?

**Comment by taymonbeal** [comment]
Not as far as I know.

**Comment by taymonbeal** [comment]
Nope not doing any more of this.
