### ISSUE TITLE
Disconnecting/Reconnecting BBS can swallow marks (e.g. for lyrics)

### ISSUE THREAD

**Issue by dspeyer** [dspeyer/ritualEngine#224]
To quote Glenn on the FB group:

ok, the lyrics thing is new because of pre-canned lyric timings
or rather they exposed it
the problem is that once we've set timers to fire events, they live in the sound buffer, but reconnection clears it
I will think about how best to deal with this, there are a couple of layers I could do that at

**Comment by gwillen** [comment]
See https://github.com/gwillen/solstice-audio-test/issues/123 .

**Comment by gwillen** [comment]
See https://github.com/gwillen/solstice-audio-test/pull/124 for the fix.

It's a big change to a core part of the mark logic, so I would love for people to review it carefully (although frankly if it didn't work I expect it would blow up very quickly.)

**Comment by gwillen** [comment]
Fixed.
