### ISSUE TITLE
Speech videos start at the beginning if you come in late

### ISSUE THREAD

**Issue by jeffkaufman** [dspeyer/ritualEngine#230]
If you join partway through a speech, the speech video still start at the beginning. Unfortunately, this means that at the end of the speech for everyone else your speech will just cut off wherever it happens to be. Better would be to start your speech at the appropriate offset one coming in late.

**Comment by taymonbeal** [comment]
I guess the way to do this would be to send a periodic "this is how far along you should be" message from the server. Currently, all messages come from client requests. @dspeyer, do you have opinions on how this should work?

**Comment by dspeyer** [comment]
Doesn't actually need to be periodic.  Just a "you are starting x seconds
late" at widget-load time.

**Comment by taymonbeal** [comment]
Not happening this week.

**Comment by dspeyer** [comment]
Fixed
