### ISSUE TITLE
Create spectator mode and require everyone else to give name on entry

### ISSUE THREAD

**Issue by taymonbeal** [dspeyer/ritualEngine#24]
Spectators have no display name or picture, do not send video or audio in Twilio or Bucket Brigade, and otherwise are invisible to everyone, but still receive all the data that everyone receives.

**Comment by taymonbeal** [comment]
@dspeyer, I'd be willing to take a stab at this myself, but I'm having a hard time finding the code governing the onboarding flow. Can you point me to it?

**Comment by dspeyer** [comment]
Client page in rituals. Py

(Sent from phone)

**Comment by taymonbeal** [comment]
Okay, I found the logic in another branch.

So what do you think would be a good way to make people enter a name before they start calibrating? Should we put this in BucketSinging.js, or should it be a separate thing?

**Comment by taymonbeal** [comment]
This has been implemented.
