### ISSUE TITLE
Create documentation for setting up a backing track + synced video

### ISSUE THREAD

**Issue by Raemon** [dspeyer/ritualEngine#26]
I'm vaguely aware that backing tracks exist now, but don't know what steps I need to take to get a fully functional backing track + synced video in ritualEngine. (In particular on the production server).

(alternately: if documentation exists somewhere, pointing me to it would also work)

**Comment by dspeyer** [comment]
Short version:

Put the backing track as a wav file in the solstice-audio-test/audio
directory.  To convert it, use
   ffmpeg -i Brighter_Than_Today.mp3 -ac 1 -ar 48000 Brighter_Than_Today.wav

Backing video should be on youtube and silent

Then copy the config from examples/Brighter_Than_Today/1.json

Note that the video in that example triggers on line 39 of the lyrics, as
we've done in past years.  If you want to trigger with the background
track, you'll need to do some coding.  Unless you have and I missed it.
But with the latest version of bbs, it should be pretty easy coding.

**Comment by taymonbeal** [comment]
No longer an outstanding issue for Solstice.
