### ISSUE TITLE
Chaos testing

### ISSUE THREAD

**Issue by taymonbeal** [dspeyer/ritualEngine#28]
Maybe we should try using the app in bad network environments, or something like that, to see if doing so surfaces any errors.

Blocked by: #27

**Comment by dspeyer** [comment]
Hang on.  This is something you're more qualified to handle.

**Comment by dspeyer** [comment]
This is definitely a thing we should do, but I don't think I'm the one who should do it.

**Comment by taymonbeal** [comment]
Closing this because it's never really done, it's just something we do as much of as we can.
