### ISSUE TITLE
Automated load testing

### ISSUE THREAD

**Issue by taymonbeal** [dspeyer/ritualEngine#30]
We mostly care about this for videoconferencing. I recently found testrtc.com, which seems like it could help.

**Comment by dspeyer** [comment]
While it doesn't do everything, or even several important things, tester.py can supply static client avatars in bulk.  It also does user avatars and tests a whole bunch of widgets.

For video client avatars, I now use:

for i in `ls *.mjpeg | shuf | head -n 7`; do nohup /opt/google/chrome/chrome  https://cpe-74-64-104-129.nyc.res.rr.com:8043/b/partake --window-size=600x200 --use-fake-device-for-media-stream --use-file-for-fake-video-capture=${i}   --disable-gpu  --user-data-dir=$(mktemp -d) --no-default-browser-check --use-fake-ui-for-media-stream --no-first-run & done

The --no-first-run tag makes it not show that annoying "make me default" dialog.  OTOH, --window-size doesn't actually seem to work.  Note that --use-fake-ui-for-media-stream is needed, despite the warning the browser will show of how it is an unsupported flag.

**Comment by taymonbeal** [comment]
We're using TestRTC for this. It seems to work well enough.
