### ISSUE TITLE
Decide what we're doing about videoconference recording

### ISSUE THREAD

**Issue by taymonbeal** [dspeyer/ritualEngine#33]
This has privacy implications so we need to think carefully about it. There are also technical things that have to happen.

**Comment by Raemon** [comment]
I think this should be towards the bottom of the nice-to-haves-for-solstice. The fact that there are some privacy concerns might just move me to "we shouldn't even bother at all."

**Comment by Raemon** [comment]
We're automatically getting recordings of most speeches and songs. Meanwhile I'm not even sure what it means to record all the videoconferencing. I'm making the call to nix this one.
