### ISSUE TITLE
Figure out if we want anything from livestreaming beyond an isolated one for each slide

### ISSUE THREAD

**Issue by taymonbeal** [dspeyer/ritualEngine#35]

**Comment by Raemon** [comment]
One thing we _might_ want is to have livestreaming that persists over a "trivia" slide. However, I've thought a bunch about Trivia and not thought of prompts that I'm actually excited about, so I'm backburnering this.

Another thing we might want is an MC that pops up in between sections. But, so far I haven't thought of stuff I'd really want the MC to say in the mainline case. Most things an MC could say might instead be sayable by other pre-recorded performres. Will think on that more.

**Comment by Raemon** [comment]
One for each slide seems fine.
