### ISSUE TITLE
Make chat history more consistent

### ISSUE THREAD

**Issue by taymonbeal** [dspeyer/ritualEngine#36]
Ideally people who joined in late or refreshed would still be able to see chat history. Note that doing this properly requires some kind of reconciliation algorithm analogous to the one React implements.

Optional.

**Comment by dspeyer** [comment]
Current system just sends 50 most recent chats, which is an easy magic number to change

**Comment by taymonbeal** [comment]
I think there might still be some edge cases in here, but we may be able to get away without worrying about them.

**Comment by taymonbeal** [comment]
Not high enough priority.
