### ISSUE TITLE
Create proper controls to mute mic and webcam

### ISSUE THREAD

**Issue by taymonbeal** [dspeyer/ritualEngine#38]
These should be used for both videoconferencing and bucket singing. They are essential for privacy.

This, along with #39, supersedes the "Twilio is not muted" control that currently exists.

**Comment by taymonbeal** [comment]
Fixed in #170.

**Comment by taymonbeal** [comment]
Actually, wait, still need control to mute webcam.

**Comment by taymonbeal** [comment]
Update: Webcam muting kinda-sorta works, but it has bugs that I don't know how to fix. I think @dspeyer or somebody would have to take a look at my work.

https://github.com/dspeyer/ritualEngine/compare/master...taymonbeal:mute-webcam

**Comment by dspeyer** [comment]
Can you describe the bugs you've seen?

**Comment by taymonbeal** [comment]
When somebody turns off their camera, they appear frozen to other people, instead of being replaced with the humanist icon like should happen. That's the biggest issue, I think.

**Comment by dspeyer** [comment]
That sounds like the correct behavior to me.  The cam-muted user is no
longer broadcasting, so they can do their secretive thing, but the sea of
faces is still a sea of faces.

**Comment by taymonbeal** [comment]
Ray declined to rule on this, so decision 2-1 is that it is not the correct behavior. So we should figure out how to fix it.

**Comment by dspeyer** [comment]
Fixed.  The key on top of what you wrote was to watch for the disabled and enabled events on the track.  And to bust caches a lot.
