### ISSUE TITLE
Create control to mute audio output

### ISSUE THREAD

**Issue by taymonbeal** [dspeyer/ritualEngine#39]
This should be used for livestream, prerecorded video, videoconferencing (in the parts where that has audio), and bucket singing.

We should not download videoconference audio that will not be used. I'm not clear on whether we can avoid downloading bucket audio in that case; it's less important in any case.

This, along with #38, supersedes the "Twilio is not muted" control that currently exists.

**Comment by Raemon** [comment]
Is this intended for individual users? I think it makes sense for people to be able to mute Twilio selectively, but if they're muting livestream or bucket output I think they should just be turnibg their system volume off

**Comment by taymonbeal** [comment]
Yes, this is intended for individual users. Usually it is considered polite to allow people to mute an individual app without muting the entire system.

**Comment by taymonbeal** [comment]
Fixed in #170.
