### ISSUE TITLE
Create control to hide videoconferencing

### ISSUE THREAD

**Issue by taymonbeal** [dspeyer/ritualEngine#40]
This should be available as a failsafe, so that if videoconferencing causes problems for people they can turn it off. (Though the user's own video feed should remain visible, if they are sending it to others.) Naturally, we should not download video that will not be shown.

**Comment by dspeyer** [comment]
I think ?notwilio does what this intends

**Comment by taymonbeal** [comment]
This is another one where I got a kinda-sorta solution working but it still seems to have some bugs that I'm not sure how to address.

https://github.com/dspeyer/ritualEngine/compare/master...taymonbeal:notwilio

**Comment by taymonbeal** [comment]
This is done now.

**Comment by taymonbeal** [comment]
I realized that I unintentionally marked this as done when it's not.

@dspeyer, do you think you can turn my partial solution into something that works without too much risk? If not, then we should declare this infeasible to fix in time.

**Comment by taymonbeal** [comment]
At this point, we cannot justify the risk of such a complex change, even to provide a failsafe against other bugs.
