### ISSUE TITLE
Do not download videoconferencing videos that are hidden by CSS

### ISSUE THREAD

**Issue by taymonbeal** [dspeyer/ritualEngine#41]
This can be done using the Twilio JS API plus IntersectionObserver.

**Comment by taymonbeal** [comment]
Daniel, is this still a thing that makes sense now that we have the images-as-fake-videos thing?

**Comment by Raemon** [comment]
More relevant is that we don't hide videos with css (I think at all?) so this seems straightforwardly ready to close.
