### ISSUE TITLE
Jointly assign buckets and Twilio rooms

### ISSUE THREAD

**Issue by taymonbeal** [dspeyer/ritualEngine#43]
I'm not clear on how this would work but it was mentioned as something we want.

**Comment by taymonbeal** [comment]
@dspeyer, is this feasible?

**Comment by taymonbeal** [comment]
By which I mean, can it be a low-risk change? (To make sure people are in the same Twilio room as others in the same bucket, I mean.) Because we're out of time for high-risk ones.

**Comment by dspeyer** [comment]
Yes.  I might be able to get it done tonight.  Testing's going to be
annoying, though.

**Comment by dspeyer** [comment]
Not tonight. Early tomorrow.

The simplest approach is to create a new set of twilio rooms every singing
slide and trust the old ones to get garbage collected.  I'm worried this
will trip something in twilio. Do you know whether there's anything to
worry about?

**Comment by taymonbeal** [comment]
We can have thousands of Twilio rooms, per the docs, and old ones definitely reliably get garbage-collected, as we've seen. The complexity here would be the timing of when we disconnect and reconnect people. Is the staggering thing I proposed earlier still in the cards?
