### ISSUE TITLE
Fix bug with videos not autoplaying on Ray’s computer

### ISSUE THREAD

**Issue by taymonbeal** [dspeyer/ritualEngine#46]

**Comment by Raemon** [comment]
I believe this one is working, but since I'm having trouble getting slides and other things to work properly, I'm not 100% sure that I've tested it properly.

**Comment by taymonbeal** [comment]
Do you mean your dev setup isn't working, or are you referring to #15? Or is this a new bug?

**Comment by Raemon** [comment]
I think this was working (although it seems to have been replaced by new confusing bug when we attempt to sync videos with backing tracks). Closing for now.
