### ISSUE TITLE
Write script for stress test

### ISSUE THREAD

**Issue by taymonbeal** [dspeyer/ritualEngine#49]

**Comment by dspeyer** [comment]
For twilio, I've been using:

for i in `ls *.mjpeg | shuf | head -n 7`; do nohup /opt/google/chrome/chrome  https://cpe-74-64-104-129.nyc.res.rr.com:8043/b/partake --window-size=100x80 --use-fake-device-for-media-stream --use-file-for-fake-video-capture=${i}   --disable-gpu  --user-data-dir=$(mktemp -d) --no-default-browser-check --use-fake-ui-for-media-stream & done

7 isn't very many, but it's what my computer can reliably handle.  Yours might be stronger.  Headless would be a huge improvement.

For other things, see tester.py

Not that everything is handled.  Just some things.

**Comment by taymonbeal** [comment]
Sorry, I meant a ritual script for the human stress test on Sunday. Automated load testing is #30.
