### ISSUE TITLE
Decide whether to move lyrics to closed-captioning track

### ISSUE THREAD

**Issue by taymonbeal** [dspeyer/ritualEngine#66]
This might be an easier and better-looking way to handle them than the manual-advancement thing we currently do.

**Comment by Raemon** [comment]
Is this dependent on using youtube in particular?

**Comment by taymonbeal** [comment]
No, we can also do this with HTML5 `<video>`. Or some other streaming service; I think they all offer some form of closed captioning.

**Comment by taymonbeal** [comment]
We're not doing this. See #111.
