### ISSUE TITLE
Make sure unsupported browsers loudly yell at you first-thing

### ISSUE THREAD

**Issue by Raemon** [dspeyer/ritualEngine#67]
(And/or fix the part where firefox breaks bucket brigade)

**Comment by Raemon** [comment]
it's possible I should do this myself, but want to finish doing some more obviously-Ray-flavored tasks first.

**Comment by Raemon** [comment]
actually, nvm this appears to already be done

**Comment by taymonbeal** [comment]
Did we do this? If so, how are we doing browser detection? I impersonated an iPhone locally in Chrome and didn't get yelled at.

**Comment by Raemon** [comment]
Right now I made it say on the front slide "please use chrome." I'll make
it also say "please use desktop"
