### ISSUE TITLE
Twilio.Video.createLocalAudioTrack() sometimes hangs

### ISSUE THREAD

**Issue by dspeyer** [dspeyer/ritualEngine#74]
When I invoke Twilio.Video.createLocalAudioTrack().then(foo()), foo sometimes just doesn't get called.  Restarting chrome fixes this.  The symptom is that the client in question cannot speak in a twilio lobby.  I am baffled as to why.

**Comment by Raemon** [comment]
Quick check if you have any other apps or tabs using video or audio at the
time that this happens? I think we had run into another bug where other
videoconferencing apps were hijacking the camera/mic so Twilio couldn't use
it. Not sure if related.

**Comment by taymonbeal** [comment]
@dspeyer, when you have a spare moment (lol) can you check whether you can still repro this? If not, let's close.

**Comment by taymonbeal** [comment]
Hmm, I seem to have run into this just now.

**Comment by taymonbeal** [comment]
Okay this was probably fixed by #190.
