### ISSUE TITLE
Bug? Testing Feature? Refreshing creates additional avatars that don't go away

### ISSUE THREAD

**Issue by Raemon** [dspeyer/ritualEngine#78]
Currently, if I refresh four times, I end up with this:

![image](https://user-images.githubusercontent.com/3246710/101236318-27ba4080-3685-11eb-8fbe-2b5692e1663a.png)

I'm guessing the issue is that ritualEngine doesn't have a way to detect if a user already exists, and then not create additional avatars or twilio feeds for them. We could either re-introduce the signup form and make them pick a unique name, or we could store a random-id as a cookie, or probably a bunch of other solutions.

(Alternately, if this is intended to be a feature that I don't understand, would appreciate some clarifying on the intent)

**Comment by taymonbeal** [comment]
I think the architecture we wanted to lean towards is more like, there's no persistent user identity, so if you refresh you do indeed get a new avatar and Twilio feed (possibly with the help of stuff you populated earlier and that was stored client-side). In which case the fix is to more promptly get rid of the old avatar and Twilio feed once they go offline.

But maybe storing some stuff persistently server-side is better. We should think about it.

**Comment by Raemon** [comment]
Daniel has since made a partial fix to this where users get discarded every 30 seconds if they haven't checked in. This isn't perfect but mostly solves the problem, at least for tomorrow's stress test.

**Comment by taymonbeal** [comment]
Do we want to store client identity persistently? If not, do we want to make the thing announce on the way out (with navigator.sendBeacon) that it's leaving, so that it disappears sooner?

**Comment by dspeyer** [comment]
Rambly braindump...

I think persistent client identity is the wrong approach.  It'll fail if
someone just closes a tab, and may cause all sorts of nasty surprises.

There might be a way to get aiohttp to notice that a request is canceled.
IIRC HTTP doesn't have a concept of cancelation, but TCP has a concept of
connection closure.  Which might or might not happen before a reload.

I'm not sure if navigator.sendBeacon could address this.  Also not sure if
it uses up valuable connection pool.

There might be an option with a beforeunload event.  It won't detect
browser crashes or kill-9s, but I think anything less.

And there's always the option of shortening the timeouts.  This increases
traffic, but may make us more robust to crappy embedded NATs.

**Comment by taymonbeal** [comment]
To be clear, the point of navigator.sendBeacon is that it's the way to talk to the server in a beforeunload event; you can't make a regular AJAX call there, or if you do it might not go through.

Not detecting browser crashes is fine.

Should I leave this assigned to you? It sounds like you have some idea of how to make it work.

**Comment by dspeyer** [comment]
I read a bunch of docs about send beacon and events and the whole thing
seems a mess.  Is it your understanding that there's a reliable way to send
an "I'm going away" message?

**Comment by taymonbeal** [comment]
Here's MDN: https://developer.mozilla.org/en-US/docs/Web/API/Navigator/sendBeacon

It's not perfectly reliable but I would expect it to be reliable enough for our purposes.

**Comment by taymonbeal** [comment]
...but if we're not sure, and you can detect cancellation server-side, that might be better. Though there's always the risk that a client disconnects between requests.

**Comment by Raemon** [comment]
fwiw I think this is sufficiently resolved by the "goes away after 30 seconds" that I wouldn't spend more cognition on it.

**Comment by taymonbeal** [comment]
Not high enough priority.
