### ISSUE TITLE
Figure out how to manually test twilio rooms

### ISSUE THREAD

**Issue by Raemon** [dspeyer/ritualEngine#81]
Today I want to make sure Twilio rooms are working correctly. This requires:

a) two people at a minimum, preferably... 5ish? (enough to check that pairs of people can get sorted into rooms, see/hear other people in that room, and see the still-image avatars of people not in their room. 5 seems better than 4 so to make sure the system works repeatedly.

b) the ability to modify how large a twilio room is (setting it temporarily to 1-2 instead of 26

c) the ability to clearly see which people are in your twilio room

**Comment by taymonbeal** [comment]
@Raemon, is this still an open issue?

**Comment by Raemon** [comment]
I guess not. (Insofar as this is still important it's probably mostly relevant to https://github.com/dspeyer/ritualEngine/issues/43)
