### ISSUE TITLE
Video-Avatars should be front-and-center-and-large

### ISSUE THREAD

**Issue by Raemon** [dspeyer/ritualEngine#86]
From what I can tell in the current implementation, twilio-avatars aren't especially prioritized in any way. Kind of the whole point of the videos is to actually see people, so they should be prioritized into the first row.

**Comment by dspeyer** [comment]
Crude prioritization is implemented

**Comment by taymonbeal** [comment]
@Raemon, is this good now?

**Comment by Raemon** [comment]
I think it might be better if more of the front-row-ones were slightly
larger, but it certainly is not at the top of my priority list.

**Comment by taymonbeal** [comment]
Should I leave it assigned to you or does Daniel have to do it?

**Comment by Raemon** [comment]
I think leave assigned to me. (in part because it's not important enough
for daniel to spend cognition on it at the moment. I'll decide if that
should change)
