### ISSUE TITLE
Crash on bucket-brigade-initialization

### ISSUE THREAD

**Issue by Raemon** [dspeyer/ritualEngine#88]
I got a crash when attempting to use bucket-brigade on Taymon's most recent branch, when first clicking the Initialize button.

(The auto-crash-report did not provide anything)

<img width="1440" alt="image" src="https://user-images.githubusercontent.com/3246710/101269950-eaa78a00-3728-11eb-9bf8-2f55321abf19.png">

<img width="1440" alt="image" src="https://user-images.githubusercontent.com/3246710/101269929-bf249f80-3728-11eb-8fbc-4824d4a80ccd.png">

**Comment by taymonbeal** [comment]
This is probably obsolete since my branch didn't get merged.
