### ISSUE TITLE
Crashed 

### ISSUE THREAD

**Issue by Raemon** [dspeyer/ritualEngine#96]
check@https://secularsolstice2020.org/widgets/BucketSinging/lib.js:20:11
concat_chunks@https://secularsolstice2020.org/widgets/BucketSinging/audiochunk.js:215:18
handle_message@https://secularsolstice2020.org/widgets/BucketSinging/app.js:838:32
handle_message@https://secularsolstice2020.org/widgets/BucketSinging/app.js:527:10

**Comment by taymonbeal** [comment]
I'm going to assume that this is a duplicate of #103.
